services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: lab_monitor
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgres://postgres:password@postgres:5432/lab_monitor
      PORT: 8000
    depends_on:
      postgres:
        condition: service_healthy
    command: sh -c "npm run migrate && npm start"

volumes:
  pgdata:
